    export const ALL_CONVERSATION_FOR_DM_REQUEST ="ALL_CONVERSATION_FOR_DM_REQUEST"
    export const ALL_CONVERSATION_FOR_DM_RESPONSE ="ALL_CONVERSATION_FOR_DM_RESPONSE"
    export const ALL_CONVERSATION_FOR_DM_FAILED ="ALL_CONVERSATION_FOR_DM_FAILED"

    export const CONVERSATION_TO_USER_FOR_DM_REQUEST = "CONVERSATION_TO_USER_FOR_DM_REQUEST"
    export const CONVERSATION_TO_USER_FOR_DM_RESPONSE = "CONVERSATION_TO_USER_FOR_DM_RESPONSE"
    export const CONVERSATION_TO_USER_FOR_DM_FAILED = "CONVERSATION_TO_USER_FOR_DM_FAILED"

    export const DELETE_CONVERSATION_FOR_DM_REQUEST = "DELETE_CONVERSATION_FOR_DM_REQUEST"
    export const DELETE_CONVERSATION_FOR_DM_RESPONSE = "DELETE_CONVERSATION_FOR_DM_RESPONSE"
    export const DELETE_CONVERSATION_FOR_DM_FAILED = "DELETE_CONVERSATION_FOR_DM_FAILED"
    
    export const SHOW_CONVERSATION_FOR_DM_REQUEST = "SHOW_CONVERSATION_FOR_DM_REQUEST"
    export const SHOW_CONVERSATION_FOR_DM_RESPONSE = "SHOW_CONVERSATION_FOR_DM_RESPONSE"
    export const SHOW_CONVERSATION_FOR_DM_FAILED = "SHOW_CONVERSATION_FOR_DM_FAILED"

    export const START_CONVERSATION_FOR_DM_REQUEST = "START_CONVERSATION_FOR_DM_REQUEST"
    export const START_CONVERSATION_FOR_DM_RESPONSE = "START_CONVERSATION_FOR_DM_RESPONSE"
    export const START_CONVERSATION_FOR_DM_FAILED = "START_CONVERSATION_FOR_DM_FAILED"

    export const UPDATE_CONVERSATION_FOR_DM_REQUEST = "UPDATE_CONVERSATION_FOR_DM_REQUEST"
    export const UPDATE_CONVERSATION_FOR_DM_RESPONSE = "UPDATE_CONVERSATION_FOR_DM_RESPONSE"
    export const UPDATE_CONVERSATION_FOR_DM_FAILED = "UPDATE_CONVERSATION_FOR_DM_FAILED"

    export const USER_FOR_DM_REQUEST = "USER_FOR_DM_REQUEST"
    export const USER_FOR_DM_RESPONSE = "USER_FOR_DM_RESPONSE"
    export const USER_FOR_DM_FAILED = "USER_FOR_DM_FAILED"
