export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

// export const ADD_NEW_LOGIN_DATA_REQUEST = "ADD_NEW_LOGIN_DATA_REQUEST"
// export const ADD_NEW_LOGIN_DATA_RESPONSE = "ADD_NEW_LOGIN_DATA_RESPONSE"
// export const ADD_NEW_LOGIN_DATA_FAILED = "ADD_NEW_LOGIN_DATA_FAILED"

// export const LOGIN_DETAILS_DATA_REQUEST = "LOGIN_DETAILS_DATA_REQUEST"
// export const LOGIN_DETAILS_DATA_RESPONSE = "LOGIN_DETAILS_DATA_RESPONSE"
// export const LOGIN_DETAILS_DATA_FAILED = "LOGIN_DETAILS_DATA_FAILED"

// export const DELETE_LOGIN_DATA_REQUEST = "DELETE_LOGIN_DATA_REQUEST"
// export const DELETE_LOGIN_DATA_RESPONSE = "DELETE_LOGIN_DATA_RESPONSE"
// export const DELETE_LOGIN_DATA_FAILED = "DELETE_LOGIN_DATA_FAILED"

// export const UPDATE_LOGIN_DATA_REQUEST = "UPDATE_LOGIN_DATA_REQUEST"
// export const UPDATE_LOGIN_DATA_RESPONSE = "UPDATE_LOGIN_DATA_RESPONSE"
// export const UPDATE_LOGIN_DATA_FAILED = "UPDATE_LOGIN_DATA_FAILED"