export const OPEN_WORK_SPACE_MODEL = "OPEN_WORK_SPACE_MODEL"

export const SHOW_WORK_SPACE = "SHOW_WORK_SPACE"

export const FETCH_WORK_SPACE_REQUEST = "FETCH_WORK_SPACE_REQUEST"
export const FETCH_WORK_SPACE_RESPONSE = "FETCH_WORK_SPACE_RESPONSE"
export const FETCH_WORK_SPACE_FAILED = "FETCH_WORK_SPACE_FAILED"

export const ADD_NEW_WORK_SPACE_REQUEST = "ADD_NEW_WORK_SPACE_REQUEST"
export const ADD_NEW_WORK_SPACE_RESPONSE = "ADD_NEW_WORK_SPACE_RESPONSE"
export const ADD_NEW_WORK_SPACE_FAILED = "ADD_NEW_WORK_SPACE_FAILED"

export const SELECT_WORK_SPACE_REQUEST = "SELECT_WORK_SPACE_REQUEST"
export const SELECT_WORK_SPACE_RESPONSE = "SELECT_WORK_SPACE_RESPONSE"
export const SELECT_WORK_SPACE_FAILED = "SELECT_WORK_SPACE_FAILED"

// export const LOGIN_DETAILS_DATA_REQUEST = "LOGIN_DETAILS_DATA_REQUEST"
// export const LOGIN_DETAILS_DATA_RESPONSE = "LOGIN_DETAILS_DATA_RESPONSE"
// export const LOGIN_DETAILS_DATA_FAILED = "LOGIN_DETAILS_DATA_FAILED"

// export const DELETE_LOGIN_DATA_REQUEST = "DELETE_LOGIN_DATA_REQUEST"
// export const DELETE_LOGIN_DATA_RESPONSE = "DELETE_LOGIN_DATA_RESPONSE"
// export const DELETE_LOGIN_DATA_FAILED = "DELETE_LOGIN_DATA_FAILED"

// export const UPDATE_LOGIN_DATA_REQUEST = "UPDATE_LOGIN_DATA_REQUEST"
// export const UPDATE_LOGIN_DATA_RESPONSE = "UPDATE_LOGIN_DATA_RESPONSE"
// export const UPDATE_LOGIN_DATA_FAILED = "UPDATE_LOGIN_DATA_FAILED"